### ISSUE TITLE
Crash after upgrade to compose 1.5

### ISSUE THREAD

**Issue by chihsuanwu** [oleksandrbalan/modalsheet#32]
After updating the compose version to 1.5, it crashes when opening the sheet.

```
java.lang.NoSuchMethodError: No static method ModalBottomSheetLayout-BzaUkTc(Lkotlin/jvm/functions/Function3;
Landroidx/compose/ui/Modifier;Landroidx/compose/material/ModalBottomSheetState;
Landroidx/compose/ui/graphics/Shape;
FJJJLkotlin/jvm/functions/Function2;
Landroidx/compose/runtime/Composer;II)V in class Landroidx/compose/material/ModalBottomSheetKt; 
or its super classes (declaration of 'androidx.compose.material.ModalBottomSheetKt' appears in <package-name>)
at eu.wewox.modalsheet.ModalSheetKt$ModalSheet$11.invoke(ModalSheet.kt:213)
```

The error message is the same as https://github.com/google/accompanist/issues/1636
